-- Product Analytics Table
CREATE TABLE IF NOT EXISTS public.product_analytics (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  product_id UUID NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  view_count INTEGER DEFAULT 0,
  add_to_cart_count INTEGER DEFAULT 0,
  purchase_count INTEGER DEFAULT 0,
  total_revenue DECIMAL(10, 2) DEFAULT 0,
  last_viewed_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(product_id)
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_product_analytics_product_id ON public.product_analytics(product_id);
CREATE INDEX IF NOT EXISTS idx_product_analytics_view_count ON public.product_analytics(view_count DESC);
CREATE INDEX IF NOT EXISTS idx_product_analytics_revenue ON public.product_analytics(total_revenue DESC);

-- Add meta fields to categories table if they don't exist
ALTER TABLE public.categories 
ADD COLUMN IF NOT EXISTS meta_title VARCHAR(255),
ADD COLUMN IF NOT EXISTS meta_description TEXT,
ADD COLUMN IF NOT EXISTS display_order INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS icon_url TEXT;

-- Create index for category ordering
CREATE INDEX IF NOT EXISTS idx_categories_display_order ON public.categories(display_order);

-- Add RLS policies for product_analytics
ALTER TABLE public.product_analytics ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to view analytics
CREATE POLICY "Allow authenticated users to view product analytics"
ON public.product_analytics
FOR SELECT
TO authenticated
USING (true);

-- Allow authenticated users to insert/update analytics
CREATE POLICY "Allow authenticated users to update product analytics"
ON public.product_analytics
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- Function to update product analytics updated_at timestamp
CREATE OR REPLACE FUNCTION update_product_analytics_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for product_analytics
DROP TRIGGER IF EXISTS update_product_analytics_timestamp ON public.product_analytics;
CREATE TRIGGER update_product_analytics_timestamp
BEFORE UPDATE ON public.product_analytics
FOR EACH ROW
EXECUTE FUNCTION update_product_analytics_timestamp();

-- Comments for documentation
COMMENT ON TABLE public.product_analytics IS 'Stores analytics data for products including views, cart adds, and purchases';
COMMENT ON COLUMN public.product_analytics.view_count IS 'Number of times product was viewed';
COMMENT ON COLUMN public.product_analytics.add_to_cart_count IS 'Number of times product was added to cart';
COMMENT ON COLUMN public.product_analytics.purchase_count IS 'Number of times product was purchased';
COMMENT ON COLUMN public.product_analytics.total_revenue IS 'Total revenue generated by this product';
